for /f %%n in ('Reg query "HKLM\SYSTEM\CurrentControlSet\Control\Class\{4D36E972-E325-11CE-BFC1-08002bE10318}" /v "*SpeedDuplex" /s ^| findstr  "HKEY"') do (
Reg.exe add "%%n" /v "AutoPowerSaveModeEnabled" /t REG_SZ /d "0" /f
Reg.exe add "%%n" /v "AutoDisableGigabit" /t REG_SZ /d "0" /f
Reg.exe add "%%n" /v "AdvancedEEE" /t REG_SZ /d "0" /f
Reg.exe add "%%n" /v "DisableDelayedPowerUp" /t REG_SZ /d "2" /f
Reg.exe add "%%n" /v "*EEE" /t REG_SZ /d "0" /f
Reg.exe add "%%n" /v "EEE" /t REG_SZ /d "0" /f
Reg.exe add "%%n" /v "EnablePME" /t REG_SZ /d "0" /f
Reg.exe add "%%n" /v "EEELinkAdvertisement" /t REG_SZ /d "0" /f
Reg.exe add "%%n" /v "EnableGreenEthernet" /t REG_SZ /d "0" /f
Reg.exe add "%%n" /v "EnableSavePowerNow" /t REG_SZ /d "0" /f
Reg.exe add "%%n" /v "EnablePowerManagement" /t REG_SZ /d "0" /f
Reg.exe add "%%n" /v "EnableDynamicPowerGating" /t REG_SZ /d "0" /f
Reg.exe add "%%n" /v "EnableConnectedPowerGating" /t REG_SZ /d "0" /f
Reg.exe add "%%n" /v "EnableWakeOnLan" /t REG_SZ /d "0" /f
Reg.exe add "%%n" /v "GigaLite" /t REG_SZ /d "0" /f
Reg.exe add "%%n" /v "NicAutoPowerSaver" /t REG_SZ /d "2" /f
Reg.exe add "%%n" /v "PowerDownPll" /t REG_SZ /d "0" /f
Reg.exe add "%%n" /v "PowerSavingMode" /t REG_SZ /d "0" /f
Reg.exe add "%%n" /v "ReduceSpeedOnPowerDown" /t REG_SZ /d "0" /f
Reg.exe add "%%n" /v "S5NicKeepOverrideMacAddrV2" /t REG_SZ /d "0" /f
Reg.exe add "%%n" /v "S5WakeOnLan" /t REG_SZ /d "0" /f
Reg.exe add "%%n" /v "ULPMode" /t REG_SZ /d "0" /f
Reg.exe add "%%n" /v "WakeOnDisconnect" /t REG_SZ /d "0" /f
Reg.exe add "%%n" /v "*WakeOnMagicPacket" /t REG_SZ /d "0" /f
Reg.exe add "%%n" /v "*WakeOnPattern" /t REG_SZ /d "0" /f
Reg.exe add "%%n" /v "WakeOnLink" /t REG_SZ /d "0" /f
Reg.exe add "%%n" /v "WolShutdownLinkSpeed" /t REG_SZ /d "2" /f
Reg.exe add "%%n" /v "JumboPacket" /t REG_SZ /d "1514" /f
Reg.exe add "%%n" /v "TransmitBuffers" /t REG_SZ /d "4096" /f
Reg.exe add "%%n" /v "ReceiveBuffers" /t REG_SZ /d "512" /f
Reg.exe add "%%n" /v "IPChecksumOffloadIPv4" /t REG_SZ /d "0" /f
Reg.exe add "%%n" /v "LsoV1IPv4" /t REG_SZ /d "0" /f
Reg.exe add "%%n" /v "LsoV2IPv4" /t REG_SZ /d "0" /f
Reg.exe add "%%n" /v "LsoV2IPv6" /t REG_SZ /d "0" /f
Reg.exe add "%%n" /v "PMARPOffload" /t REG_SZ /d "0" /f
Reg.exe add "%%n" /v "PMNSOffload" /t REG_SZ /d "0" /f
Reg.exe add "%%n" /v "TCPChecksumOffloadIPv4" /t REG_SZ /d "0" /f
Reg.exe add "%%n" /v "TCPChecksumOffloadIPv6" /t REG_SZ /d "0" /f
Reg.exe add "%%n" /v "UDPChecksumOffloadIPv6" /t REG_SZ /d "0" /f
Reg.exe add "%%n" /v "UDPChecksumOffloadIPv4" /t REG_SZ /d "0" /f
Reg.exe add "%%n" /v "RSS" /t REG_SZ /d "1" /f
Reg.exe add "%%n" /v "*NumRssQueues" /t REG_SZ /d "2" /f
Reg.exe add "%%n" /v "RSSProfile" /t REG_SZ /d "3" /f
Reg.exe add "%%n" /v "*FlowControl" /t REG_SZ /d "0" /f
Reg.exe add "%%n" /v "FlowControlCap" /t REG_SZ /d "0" /f
Reg.exe add "%%n" /v "RxAbsIntDelay" /t REG_SZ /d "0" /f
Reg.exe add "%%n" /v "TxIntDelay" /t REG_SZ /d "0" /f
Reg.exe add "%%n" /v "TxAbsIntDelay" /t REG_SZ /d "0" /f
Reg.exe add "%%n" /v "FatChannelIntolerant" /t REG_SZ /d "0" /f
)
